spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /dbase
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false